### ISSUE TITLE
Very slick. How about Yarn?

### ISSUE THREAD

**Issue by kylecordes** [tenjaa/docker-java-chrome-nodejs#1]
This is slick. I had something local, and now just point to this instead.

One idea though... how about Yarn in-the-box?

**Comment by tenjaa** [comment]
Currently no there aren't any plans.
As soon as we switch to yarn, we will update this image (or better create a new one).

But feel free to fork this and just take yarn instead :)

**Comment by kylecordes** [comment]
Thanks... of course a fork and Dockerfile are straightforward... any advice how to most easily do (as the README says) "Rebuilds automatically on push to git and updated node, openjdk or debian docker image" ?

**Comment by tenjaa** [comment]
Just create a docker hub account.
There you can create automated builds that linked to a github repository.
After creating them, you can reference in the settings multiple other docker images. Everytime when one of these images gets updated, your image will be rebuild

**Comment by kylecordes** [comment]
Thank you for the tip, that is clever. For some reason I had thought of that feature as, "I am building off of the node image, so I need to know when it changed". But you can (mis?)use it as "I'm not building off the node image, but I do use node; so when the node image changes that probably means I need to rebuild". Very slick.
